modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://example.com/" #optional
[[mods]] #mandatory
modId="rgbblocks" #mandatory
version="0.5" #mandatory
displayName="RGB Blocks" #mandatory
updateJSONURL="http://example.com/" #optional
displayURL="http://example.com/" #optional
logoFile="" #optional
credits="" #optional
authors="PlatinPython" #optional
description='''
Blocks in almost every color you can imagine
'''
[[dependencies.rgbblocks]] #optional
  modId="forge" #mandatory
  mandatory=true #mandatory
  versionRange="[31,)" #mandatory
  ordering="NONE"
  side="BOTH"

[[dependencies.rgbblocks]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.15.2]"
  ordering="NONE"
  side="BOTH"
