modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/PlatinPython/RGBBlocks/issues"

[[mods]]
  modId="rgbblocks"
  version="${file.jarVersion}"
  displayName="RGB Blocks"
  description="Blocks in almost all colors you can imagine."
  logoFile="logo.png"
  logoBlur=true
  credits="Thanks TobiBenzi for the logo and some textures, Thanks XFactHD for implementing the CTM Model"
  authors="PlatinPython"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/rgb-blocks-forge"

[[dependencies.rgbblocks]]
  modId="forge"
  mandatory=true
  versionRange="[40,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.rgbblocks]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.18.2,)"
  ordering="NONE"
  side="BOTH"
