modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPL-3.0 License"
issueTrackerURL="https://github.com/PlatinPython/RGBBlocks/issues" #optional

[[mods]] #mandatory
modId="rgbblocks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="RGB Blocks" #mandatory
logoFile="logo.png" #optional
credits="Thanks TobiBenzi for the logo" #optional
authors="PlatinPython" #optional
description='''
Blocks in almost all colors you can imagine.
'''

[[dependencies.rgbblocks]] #optional
  modId="forge" #mandatory
  mandatory=true #mandatory
  versionRange="[34,)" #mandatory
  ordering="NONE"
  side="BOTH"

[[dependencies.rgbblocks]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.3,)"
  ordering="NONE"
  side="BOTH"


[[dependencies.rgbblocks]]
  modId="ctm"
  mandatory=false
  versionRange="[MC1.16.1-1,)"
  ordering="NONE"
  side="CLIENT"
