modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/PlatinPython/RGBBlocks/issues"

[[mods]]
  modId="rgbblocks"
  version="${file.jarVersion}"
  displayName="RGB Blocks"
  description="Blocks in almost all colors you can imagine."
  logoFile="logo.png"
  logoBlur=true
  credits="Thanks TobiBenzi for the logo and some textures"
  authors="PlatinPython"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/rgb-blocks-forge"

[[dependencies.rgbblocks]]
  modId="forge"
  mandatory=true
  versionRange="[37,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.rgbblocks]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.17.1,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.rgbblocks]]
  modId="ctm"
  mandatory=false
  versionRange="[MC1.16.1-1,)"
  ordering="NONE"
  side="CLIENT"
